version: "2"
services:
  
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres # Big THX to Amir.SH!!! for simplifiying DB initialization
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

  #zookeeper:
  #  image: wurstmeister/zookeeper
  #  container_name: zookeeper
  #  ports:
  #    - "2181:2181"
  #kafka:
  #  image: wurstmeister/kafka 
  #  container_name: kafka
  #  ports: 
   #   - "9092:9092"        
   # environment:
   #   KAFKA_ADVERTISED_HOST_NAME: kafka
   #   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
   #   KAFKA_CREATE_TOPICS: "notif3:1:1"
   #   KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
   # depends_on:
   #   - zookeeper
   # links:
   #   - zookeeper:zk   
  buildit-test:
    build: 
      context: .
      dockerfile: test/Dockerfile
    command: "go test ./test/create_plant_hire_test.go" 


  buildit:  
    build: . # uses Dockerfile in root dir to build the image
    ports:
      - "8081:8080"

    environment:
      #KAFKA_URL: kafka:9092
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    restart: on-failure  
    #depends_on: [postgres,kafka,zookeeper]   
    depends_on: [db]   

    #links: [kafka,zookeeper]

